Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(model_trainer.py:17580): Gdk-CRITICAL **: 13:54:14.128: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "model_trainer.py", line 42, in <module>
    pre_trained_net.load_state_dict(torch.load('mnist_unilenet_w_acc_95.pt', map_location=torch.device('cpu')))
  File "/home/naddeok5/.local/lib/python3.6/site-packages/torch/serialization.py", line 525, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/naddeok5/.local/lib/python3.6/site-packages/torch/serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/naddeok5/.local/lib/python3.6/site-packages/torch/serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'mnist_unilenet_w_acc_95.pt'
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(model_trainer.py:18526): Gdk-CRITICAL **: 14:03:19.602: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
