Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(model_trainer.py:25366): Gdk-CRITICAL **: 07:58:33.714: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
0.3053
Traceback (most recent call last):
  File "model_trainer.py", line 46, in <module>
    # Define File Names
NameError: name 'rand_accuracy' is not defined
